/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_incremental_updating_TestLinkSo */

#ifndef _Included_com_example_demo_incremental_updating_TestLinkSo
#define _Included_com_example_demo_incremental_updating_TestLinkSo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_incremental_updating_TestLinkSo
 * Method:    getThirdString
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_incremental_1updating_TestLinkSo_getThirdString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
