/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_incremental_updating_TestLinkSoTwo */

#ifndef _Included_com_example_demo_incremental_updating_TestLinkSoTwo
#define _Included_com_example_demo_incremental_updating_TestLinkSoTwo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_incremental_updating_TestLinkSoTwo
 * Method:    getThirdString
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_incremental_1updating_TestLinkSoTwo_getThirdString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
