/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_zhang_TestJni */

#ifndef _Included_com_zhang_TestJni
#define _Included_com_zhang_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhang_TestJni
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhang_TestJni_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_zhang_TestJni
 * Method:    invokeJniToJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhang_TestJni_invokeJniToJava
  (JNIEnv *, jobject);

/*
 * Class:     com_zhang_TestJni
 * Method:    giveArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_zhang_TestJni_giveArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_zhang_TestJni
 * Method:    cached
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhang_TestJni_cached
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
